# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: android_env/proto/raw_observation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='android_env/proto/raw_observation.proto',
  package='android_env',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'android_env/proto/raw_observation.proto\x12\x0b\x61ndroid_env\"\xa5\x01\n\x0eRawObservation\x12\x14\n\x0ctimestamp_us\x18\x01 \x01(\x03\x12\x31\n\x06screen\x18\x02 \x01(\x0b\x32!.android_env.RawObservation.Image\x1aJ\n\x05Image\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x14\n\x0cnum_channels\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x62\x06proto3'
)




_RAWOBSERVATION_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='android_env.RawObservation.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='android_env.RawObservation.Image.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='android_env.RawObservation.Image.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_channels', full_name='android_env.RawObservation.Image.num_channels', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='android_env.RawObservation.Image.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=222,
)

_RAWOBSERVATION = _descriptor.Descriptor(
  name='RawObservation',
  full_name='android_env.RawObservation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp_us', full_name='android_env.RawObservation.timestamp_us', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='screen', full_name='android_env.RawObservation.screen', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RAWOBSERVATION_IMAGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=222,
)

_RAWOBSERVATION_IMAGE.containing_type = _RAWOBSERVATION
_RAWOBSERVATION.fields_by_name['screen'].message_type = _RAWOBSERVATION_IMAGE
DESCRIPTOR.message_types_by_name['RawObservation'] = _RAWOBSERVATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RawObservation = _reflection.GeneratedProtocolMessageType('RawObservation', (_message.Message,), {

  'Image' : _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
    'DESCRIPTOR' : _RAWOBSERVATION_IMAGE,
    '__module__' : 'android_env.proto.raw_observation_pb2'
    # @@protoc_insertion_point(class_scope:android_env.RawObservation.Image)
    })
  ,
  'DESCRIPTOR' : _RAWOBSERVATION,
  '__module__' : 'android_env.proto.raw_observation_pb2'
  # @@protoc_insertion_point(class_scope:android_env.RawObservation)
  })
_sym_db.RegisterMessage(RawObservation)
_sym_db.RegisterMessage(RawObservation.Image)


# @@protoc_insertion_point(module_scope)
